name: "sit-portal-client"

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: sit-portal-client
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped