import type { Certificate } from "./certificate";

export const certificates: Certificate[] = [
  {
    id: 1,
    name: "AWS Cloud Practitioner",
    issuer: "Amazon Web Services",
    uploadDate: "2024-01-15",
    status: "verified",
    verificationProgress: 100,
    expiryDate: "2027-01-15",
    credentialId: "AWS-CP-2024-001",
    category: "Cloud Computing",
    fileSize: "2.4 MB",
    fileType: "PDF",
  },
  {
    id: 2,
    name: "Google Analytics Certified",
    issuer: "Google",
    uploadDate: "2024-01-10",
    status: "pending",
    verificationProgress: 75,
    expiryDate: "2025-01-10",
    credentialId: "GA-2024-002",
    category: "Digital Marketing",
    fileSize: "1.8 MB",
    fileType: "PDF",
  },
  {
    id: 3,
    name: "Microsoft Azure Fundamentals",
    issuer: "Microsoft",
    uploadDate: "2024-01-08",
    status: "rejected",
    verificationProgress: 0,
    expiryDate: "2026-01-08",
    credentialId: "AZ-900-2024-003",
    rejectionReason:
      "Certificate image quality too low. Please upload a higher resolution image.",
    category: "Cloud Computing",
    fileSize: "3.2 MB",
    fileType: "JPG",
  },
];
