FROM node:22.19-alpine3.22 AS builder

WORKDIR /client

COPY package.json package-lock.json* ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:1.29.1-alpine

COPY --from=builder /client/dist /var/www/sitportal.test/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
